name: build_hise_macos
on: [push]
jobs:
  build-hise_macos:
    runs-on: [self-hosted, macos]
    steps:
      - name: Checkout HISE repository
        uses: actions/checkout@v1
      - name: Build HISE on macOS
        working-directory: ${{ github.workspace }}/tools/auto_build/
        run: sh ./01_BuildHISE.sh
